sudo:
  false

language: node_js

node_js:
  - "stable"

notifications:
  email: false

env:
  - NODE_ENV=test

install:
  - cd ./website/backend
  - npm ci
  - cd ../frontend
  - npm ci
  - cd ../backend

script:
  - npm run test-coverage
  - npm run cypress:test